;����װ������,create by ChenWeiMing
[Main]
Left=144
Top=100
Width=433
Height=301
Image=\Spr\Ui3\����װ��\��ͼ.spr
Trans=0
Moveable=1

;dong btn
[CloseBtn]
Left=145
Top=277
Width=70
Height=40
Up=0
Down=1
Over=2
OverFrame=2
Trans=0
Image=\spr\Ui3\����װ��\�ر�.spr

;tinh luyen
[CompoundBtn]
Left=20
Top=22
Width=79
Height=20
Up=0
Down=1
Trans=0
CheckBox=1
Image=\spr\Ui3\����װ��\������ҳͼ��.spr

;lay
[CryoliteBtn]
Left=
Top=
Width=79
Height=20
Up=0
Down=1
Trans=0
CheckBox=1
Image=\spr\Ui3\����װ��\������ҳͼ��.spr

;che tao
[PropMineBtn]
Left=
Top=
Width=79
Height=20
Up=0
Down=1
Trans=0
CheckBox=1
Image=\spr\Ui3\����װ��\������ҳͼ��.spr

;
[DistillBtn]
Left=98
Top=22
Width=79
Height=20
Up=0
Down=1
Trans=0
CheckBox=1
Image=\spr\Ui3\����װ��\��ȡ��ҳͼ��.spr

;
[ForgeBtn]
Left=176
Top=22
Width=79
Height=20
Up=0
Down=1
Trans=0
CheckBox=1
Image=\spr\Ui3\����װ��\�����ҳͼ��.spr

;kham nam
[EnchaseBtn]
Left=255
Top=22
Width=79
Height=20
Up=0
Down=1
Trans=0
CheckBox=1
Image=\spr\Ui3\����װ��\��Ƕ��ҳͼ��.spr

;do pho
[AtlasBtn]
Left=334
Top=22
Width=79
Height=20
Up=0
Down=1
Trans=0
CheckBox=1
Image=\spr\Ui3\����װ��\ͼ�׷�ҳͼ��.spr

;[CheTao]
;Left=150
;Top=4
;Width=112
;Height=0
;Font=16
;HAlign=1
;Color=255,255,255

;���ֹ���˵��
[RuleInfo]
Compound=N�ng c�p huy�n tinh: C�n 1 vi�n Huy�n Tinh v� 5000 l��ng, nh�p chu�t ph�i 3 l�n v�o Huy�n Tinh r�i ch�n Tinh Luy�n !
CompoundRule=Ph�i trang s�c: c�n 1 d�y chuy�n, h��ng nang, ng�c b�i (Xanh ho�c tr�ng) b� v�o r�i nh�n Tinh Luy�n !
CompoundRule2=C� th� ch� t�o trang b� m�u xanh ho�c tr�ng t� c�c trang s�c c� s�n. ��t nh�n, d�y chuy�n v� ng�c b�i/h��ng nang v�o c�c � t��ng �ng.
UpCryolite=
UpCryoliteRule=
UpPropMine=Ch� bi�n kho�ng th�ch: S� d�ng nguy�n li�u kho�ng th�ch �� t�o ra v�t ph�m c� gi� tr�. ��t c�c kho�ng th�ch v�o 3 � t��ng �ng.
UpPropMineRule=Kho�ng th�ch c�n thi�t cho qu� tr�nh ch� bi�n. T� l� th�nh c�ng ph� thu�c v�o ch�t l��ng nguy�n li�u �� s� d�ng. 
Distill=Nguy�n li�u: thu�c t�nh nguy�n kho�ng, nguy�n th�ch, huy�n tinh, trang b� m�u xanh, 5000 l��ng, Kho�ng th�ch th�n b�
DistillRule=Mu�n gia t�ng ph�m ch�t th� c� th� th�m v�o: Th�y Tinh 3 m�u t�y th�ch, Ph�c Duy�n ti�u, trung, ��i.
Forge=Nguy�n li�u c�n thi�t: Trang b� xanh ho�c tr�ng, Huy�n Tinh ( Ph�m ch�t c�ng cao th� trang b� Huy�n Tinh s� t�t h�n )
ForgeRule=
Enchase=Nguy�n li�u c�n thi�t: Trang b� Huy�n Tinh, 10000 l��ng, Huy�n Tinh t�y ph�m ch�t, kho�ng th�ch �� h�t thu�c t�nh t�y h�   
EnchaseRule=C� th� cho th�m Th�y Tinh ( g�m 3 m�u), ph�c duy�n ti�u, trung, ��i �� gia t�ng t� l� th�nh c�ng !
Atlas=
AtlasRule=
