;��ʯ�ϳ�,create by chenweiming 2004-12-17
[Main]
Left=19
Top=43
Width=395
Height=233
Moveable=0
Image=\Spr\Ui3\����װ��\��ҳ�ϳ�.spr

;��ʯ1
[Ore1]
Left=89
Top=23
Width=58
Height=54
Tip=DAT HUYEN TINH 1 VAO DAY (Box1)						   

;��ʯ2
[Ore2]
Left=26
Top=132
Width=58
Height=54
Tip=DAT HUYEN TINH 3 VAO DAY (Box3)								   

;��ʯ3
[Ore3]
Left=150
Top=132
Width=58
Height=54
Tip=DAT HUYEN TINH 2 VAO DAY (Box2)						   

;������ʯ
[NewOre]
Left=98
Top=101
Width=33
Height=33

;�ϳ���˵��
[GuideList]
Left=243
Top=2
Width=132
Height=210
Font=14
MsgLineCount=10,500
MaxMsgCount=40
MsgColor=218,255,165
MsgBorderColor=23,68,0
Selable=0

;�϶���
[GuideList_Scroll]
Left=378
Top=0
Width=13
Height=202
Type=1
Min=0
Max=20
PageSize=1
SlideBegin=14
SlideEnd=193

;�϶�����ť
[GuideList_Scroll_Btn]
Left=0
Top=0
Width=13
Height=27
Up=0
Down=0
Over=0
OverFrame=0
Trans=0
Image=\Spr\Ui3\����qq\ͨ���϶���.spr

;�ϳɰ�ť
[CompoundBtn]
Left=246
Top=208
Width=64
Height=20
Up=0
Down=1
Over=2
OverFrame=2
NoOverSound=0
SendHoldMsg=0
Image=\Spr\Ui3\����װ��\����.spr
Tip=Tinh Luyen

;ȡ����ť
[CancleBtn]
Left=330
Top=208
Width=64
Height=20
Up=0
Down=1
Over=2
overFrame=2
NoOverSound=0
SendHoldMsg=0
Image=\Spr\Ui3\����װ��\ȡ��.spr
Tip=Huy bo

;Hieu ung hinh anh dong 1
[Effect_0]
Left=57
Top=-52
Width=120
Height=200
;Image=\spr\Ui3\����װ��\�ϳ���Ч1.spr
;Image=\Spr\Ui3\UiCompoundItem\Effect.spr
Image=\Spr\Ui3\UiOutInItem\Effect.spr
Moveable=0
Trans=0

;Hieu ung hinh anh dong 2
[Effect_1]
Left=-6
Top=60
Width=120
Height=200
;Image=\spr\Ui3\����װ��\�ϳ���Ч1.spr
;Image=\Spr\Ui3\UiCompoundItem\Effect.spr
Image=\Spr\Ui3\UiOutInItem\Effect.spr
Moveable=0
Trans=0

;Hieu ung hinh anh dong 3
[Effect_2]
Left=120
Top=60
Width=120
Height=200
;Image=\spr\Ui3\����װ��\�ϳ���Ч1.spr
;Image=\Spr\Ui3\UiCompoundItem\Effect.spr
Image=\Spr\Ui3\UiOutInItem\Effect.spr
Moveable=0
Trans=0

;��һ
[Box_0]
Pos=115,49

;���
[Box_1]
Pos=177,159

;����
[Box_2]
Pos=51,159

;���������ɫ
[TextColor]
Font=130,70,20
Border=0,0,0

;���ؽ����Ӧ����ʾ��Ϣ
[ReturnInfo]
;error_unknown = -1,
1=Xuat 1 loi sai.
;foundry_succeed = 0,	
2=Xin chuc mung, ban nhan duoc pham chat da cao.
;foundry_failure = 1,
3=�˴κϳ�ʧ��,�����������ʧһ���򼸼�ԭ���ϡ�
;foundry_no_money = 2,
4=�Բ���,�����ϴ����ʽ���,���ܽ��д��������
;foundry_level_full = 3,
5=���Ŀ�ʯ�ȼ��Ѿ��ﵽ������,������������.
;foundry_lack_resource,
6=���ϲ�����Ҫ��,���������Ҫ�Ĳ��ϰ�Ҫ���������³���.
;foundry_level_differ,
7=���Ŀ�ʯ�ȼ���һ��,��ѡ��ȼ�һ�µĿ�ʯ������.
;foundry_no_magic,
8=��ִ���˷Ƿ�����!
;foundry_series_differ,
9=���Ŀ�ʯ���в�һ��,��ѡ������һ�µĿ�ʯ������.
;foundry_not_accord,
10=���ϲ�����Ҫ��,���������Ҫ�Ĳ��ϰ�Ҫ���������³���.
;foundry_accord_rule,
11=�˴κϳ�ʧ��,�����������ʧһ���򼸼�ԭ����.
;foundry_incorrect_opera,
12=��ִ���˷Ƿ�����.

